[tool.poetry]
name = "proxy-ref"
version = "0.1.0"
description = "Referencia de proxy para adfree-protocol"
authors = ["LUBEN09"]

[tool.poetry.dependencies]
python = ">=3.9"
aiohttp = "^3.9.0"
cryptography = "42.0.0"
prometheus-client = "0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
 